# Generated by Django 6.0.6 on 2026-07-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("face_weight", models.DecimalField(decimal_places=3, default=0.25, max_digits=4)),
                ("smile_weight", models.DecimalField(decimal_places=3, default=0.25, max_digits=4)),
                (
                    "motion_weight",
                    models.DecimalField(decimal_places=3, default=0.25, max_digits=4),
                ),
                ("audio_weight", models.DecimalField(decimal_places=3, default=0.25, max_digits=4)),
                ("window_size_seconds", models.PositiveSmallIntegerField(default=4)),
                ("step_seconds", models.PositiveSmallIntegerField(default=2)),
                ("min_clip_length_seconds", models.PositiveSmallIntegerField(default=4)),
                ("min_gap_seconds", models.PositiveSmallIntegerField(default=2)),
                ("peak_count", models.PositiveSmallIntegerField(default=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("ingest", "Ingest"),
                            ("clip_extraction", "Clip Extraction"),
                            ("score", "Score"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("stderr", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="library.video",
                    ),
                ),
                (
                    "scoring_params",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="pipeline.scoringparams",
                    ),
                ),
            ],
        ),
    ]
