# Generated by Django 6.0.6 on 2026-07-07 10:34

from django.db import migrations


def seed_default_scoring_params(apps, schema_editor):
    ScoringParams = apps.get_model("pipeline", "ScoringParams")
    if not ScoringParams.objects.exists():
        ScoringParams.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_default_scoring_params, migrations.RunPython.noop),
    ]
