# Generated by Django 6.0.6 on 2026-07-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_seed_default_scoring_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("probe", "Probe"),
                    ("ingest", "Ingest"),
                    ("clip_extraction", "Clip Extraction"),
                    ("score", "Score"),
                ],
                max_length=32,
            ),
        ),
    ]
