# Generated by Django 6.0.6 on 2026-07-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_probe_stage_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="silence_penalty_weight",
            field=models.DecimalField(decimal_places=3, default=0.1, max_digits=4),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="silence_rms_threshold",
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=6),
        ),
    ]
