# Generated by Django 6.0.6 on 2026-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_scoring_silence_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="smoothing_window_count",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
