# Generated by Django 6.0.6 on 2026-07-08 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0003_tag_slug_label"),
        ("pipeline", "0005_scoringparams_smoothing_window_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="combine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="library.combine",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("probe", "Probe"),
                    ("ingest", "Ingest"),
                    ("clip_extraction", "Clip Extraction"),
                    ("score", "Score"),
                    ("combine_export", "Combine Export"),
                ],
                max_length=32,
            ),
        ),
    ]
