# Generated by Django 6.0.6 on 2026-08-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0007_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="detect_max_width_pixels",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
