# Generated by Django 6.0.6 on 2026-08-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0007_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="target_clip_length_seconds",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="scoringparams",
            name="min_gap_seconds",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
