# Generated by Django 6.0.6 on 2026-08-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0008_scoringparams_detect_max_width_pixels"),
        ("pipeline", "0008_scoringparams_target_clip_length_seconds_and_more"),
    ]

    operations = []
