# Generated by Django 6.0.6 on 2026-08-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0009_merge_20260828_0655"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="face_min_neighbors",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="face_scale_factor",
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=3),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="smile_min_neighbors",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="smile_roi_min_height_pixels",
            field=models.PositiveSmallIntegerField(default=64),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="smile_scale_factor",
            field=models.DecimalField(decimal_places=2, default=1.3, max_digits=3),
        ),
        migrations.AlterField(
            model_name="scoringparams",
            name="detect_max_width_pixels",
            field=models.PositiveSmallIntegerField(default=1920),
        ),
    ]
