# Generated by Django 6.0.6 on 2026-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0010_scoringparams_face_min_neighbors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("probe", "Probe"),
                    ("ingest", "Ingest"),
                    ("transcode", "Transcode"),
                    ("clip_extraction", "Clip Extraction"),
                    ("score", "Score"),
                    ("contact_sheet", "Contact Sheet"),
                    ("combine_export", "Combine Export"),
                ],
                max_length=32,
            ),
        ),
    ]
