# Generated by Django 6.0.6 on 2026-08-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0011_alter_job_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="frames_per_window",
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
