# Generated by Django 6.0.6 on 2026-09-13 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0009_video_thumbnail_path"),
        ("pipeline", "0012_scoringparams_frames_per_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="library.video",
            ),
        ),
    ]
