# Generated by Django 6.0.6 on 2026-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0013_alter_job_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="clip_length_mode",
            field=models.CharField(
                choices=[("fixed", "Fixed length"), ("variable", "Variable length")],
                default="fixed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="max_clip_length_seconds",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="plateau_score_ratio",
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=3),
        ),
    ]
