# Generated by Django 6.0.6 on 2026-09-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0014_scoringparams_clip_length_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="min_peak_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
