# Generated by Django 6.0.6 on 2026-09-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0015_scoringparams_min_peak_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="still_count",
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="still_min_gap_seconds",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="still_min_quality_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scoringparams",
            name="still_sample_step_seconds",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("probe", "Probe"),
                    ("ingest", "Ingest"),
                    ("transcode", "Transcode"),
                    ("clip_extraction", "Clip Extraction"),
                    ("still_extraction", "Still Extraction"),
                    ("score", "Score"),
                    ("contact_sheet", "Contact Sheet"),
                    ("combine_export", "Combine Export"),
                ],
                max_length=32,
            ),
        ),
    ]
