# Generated by Django 6.0.6 on 2026-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0016_scoringparams_still_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoringparams",
            name="face_detection_confidence",
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
